version: '3.8'

services:
  goss:
    build:
      context: .
      dockerfile: Dockerfile
    image: goss:latest
    container_name: goss
    environment:
      - LMSTUDIO_API_KEY=${LMSTUDIO_API_KEY:-}
      - LMSTUDIO_BASE_URL=${LMSTUDIO_BASE_URL:-http://host.docker.internal:1234/v1}
      - DEFAULT_MODEL=${DEFAULT_MODEL:-openai/gpt-oss-20b}
    volumes:
      - ./goss_config.json:/home/appuser/goss_config.json:ro
      - ./logs:/home/appuser/logs
    networks:
      - goss-network
    # Use host networking on Linux to access LM Studio on host
    # network_mode: host  # Uncomment on Linux
    extra_hosts:
      - "host.docker.internal:host-gateway"  # For Docker Desktop
    stdin_open: true
    tty: true
    command: ["--base-url", "http://host.docker.internal:1234/v1"]
    restart: unless-stopped

networks:
  goss-network:
    driver: bridge